# Generated by Django 4.0 on 2021-12-22 18:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер квартиры')),
                ('adress', models.CharField(max_length=50, verbose_name='Адрес дома')),
                ('floor', models.CharField(max_length=2, verbose_name='Этаж')),
                ('square', models.IntegerField(default=5, verbose_name='Площадь')),
                ('price', models.IntegerField(default=25, verbose_name='Цена')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='CounterAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('passport', models.CharField(max_length=10, verbose_name='Пасспортные данные')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес регистрации')),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=25, verbose_name='Номер счёта')),
                ('sum', models.IntegerField(default=25, verbose_name='Сумма к оплате')),
                ('dateOfPayment', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оплаты')),
                ('dateOfIssue', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выставления счёта')),
            ],
            options={
                'verbose_name': 'Cчёт',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('position', models.CharField(max_length=20, verbose_name='Должность')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес офиса')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('quantityOfDeals', models.CharField(max_length=5, verbose_name='Количество сделок')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.RemoveField(
            model_name='deal',
            name='date',
        ),
        migrations.AddField(
            model_name='deal',
            name='dateOfCon',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заключения'),
        ),
        migrations.AddField(
            model_name='deal',
            name='dateOfReg',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contract',
            field=models.IntegerField(default=0, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='deal',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apart', to='base.apartment', verbose_name='Квартира'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='counteragent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='base.counteragent', verbose_name='Контрагент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='base.invoice', verbose_name='Счёт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deal_manager', to='base.manager', verbose_name='Менеджер'),
            preserve_default=False,
        ),
    ]
