# Generated by Django 4.0 on 2021-12-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_apartment_counteragent_invoice_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='adress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='name',
        ),
        migrations.AddField(
            model_name='deal',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='Номер квартиры'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Продана'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Номер счёта'),
        ),
    ]
