# Generated by Django 4.0 on 2021-12-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_adress_apartment_address_remove_deal_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='title',
        ),
    ]
