# Generated by Django 4.0 on 2021-12-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_deal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='status_of_act',
            field=models.BooleanField(default=False, verbose_name='Статус акта приема-передачи'),
        ),
    ]
